#!/bin/bash

set ${CHANG_SET:--eu}

cd $(dirname $(readlink $BASH_SOURCE))

for source in sources/*.sh; do
  f=$source
  f=${f##*/}
  f=${f%%.sh}

  if ! type $f &>/dev/null; then
    source $source
  fi
done

export CHANG_HOME=${CHANG_HOME:-$HOME/.chang}
export CHANG_REV_PROXY_ENABLED=${CHANG_REV_PROXY_ENABLED:-true}
export CHANG_REV_PROXY_PORT=${CHANG_REV_PROXY_PORT:-80}
export CHANG_REV_PROXY_BIND=${CHANG_REV_PROXY_BIND:-127.0.0.1}
export CHANG_REV_PROXY_CONTAINER=${CHANG_REV_PROXY_CONTAINER:-changrevproxy}
export CHANG_REV_PROXY_IMAGE=${CHANG_REV_PROXY_IMAGE:-majkel/chang-rev-proxy}
export CHANG_REV_PROXY_EXTRA_PORTS_PREFIX=${CHANG_REV_PROXY_EXTRA_PORTS_PREFIX:-808}

case "${1:-}" in
  ""|start)
    if ! chang_rev_proxy_running; then
      chang_rev_proxy_remove
      chang_rev_proxy_start
    fi
    ;;
  stop)
    chang_notice "Stopping chang-rev-proxy"
    chang_rev_proxy_stop
    ;;
  restart)
    chang_notice "Restarting chang-rev-proxy"
    chang_rev_proxy_restart
    ;;
  install)
    chang_rev_proxy_install "${@:2}"
    ;;
  reset)
    chang_rev_proxy_reset "$2"
    ;;
  attach)
    chang_rev_proxy_attach
    ;;
  *)
    chang_error "Usage: chang-rev-proxy [start|stop|install]"
    ;;
esac
